softeerbootcamp/Team1-TDD

front-end/src/components/Navbar/Navbar.scss, front-end/src/components/Navbar/Navbar.ts, front-end/src/core/Router.ts, front-end/src/styles/main.scss
- #13 
- navbar를 만들기 위함이에요
- 네이게이션바 마크업 및 라우터 구성을 했어요
- 아직 디자인과 컴포넌트 렌더가 안돼요. 기본적인 마크업과 라우터만 구성해 놨어요.
- 네비게이션바를 클릭하면 console이 나와요.
- 디자인을 적용할 계획이에요
- 컴포넌트가 만들어지면 라우팅을 적용할 예정이에요
=> 네이게이션바 마크업 및 라우터 구성

back-end/src/main/java/com/tdd/backend/post/Appointment.java, back-end/src/main/java/com/tdd/backend/post/Category.java, back-end/src/main/java/com/tdd/backend/post/DriveCareer.java, back-end/src/main/java/com/tdd/backend/post/Location.java, back-end/src/main/java/com/tdd/backend/post/Option.java, back-end/src/main/java/com/tdd/backend/post/Options.java, back-end/src/main/java/com/tdd/backend/post/Post.java, back-end/src/main/java/com/tdd/backend/post/PostRepository.java, back-end/src/main/java/com/tdd/backend/post/PostService.java, back-end/src/main/java/com/tdd/backend/user/User.java, back-end/src/main/java/com/tdd/backend/user/UserRepository.java, back-end/src/main/java/com/tdd/backend/user/UserService.java, back-end/src/main/resources/schema.sql, back-end/src/test/java/com/tdd/backend/post/PostServiceTest.java, back-end/src/test/java/com/tdd/backend/user/UserServiceTest.java
- resolved #17 
- 설계한 ERD 기반으로 코드 레벨에서의 도메인 생성
- 생성된 도메인에 대한 간단한 insert 테스트 코드 작성
- 백엔드 멤버간 페어 프로그래밍으로 진행함.
- 객체간 매핑 관계나 Enum 클래스 처리 등 리팩토링 여지 있음.
- 설계를 기반으로 서비스 기능에 맞추어 확장
-  패키지 분리 등, 상태 (Status) 등 Enum 클래스화 예정.
=> Be/feature/#17 도메인 설계

front-end/src/components/Navbar/Navbar.module.scss, front-end/src/components/Navbar/Navbar.ts, front-end/src/styles/main.scss
- #23 
- 어떤 페이지의 기능이 멋져보였어요
- 네비게이션 상단바에 잔여 스크롤 표시바를 구현했어요
- 스크린 샷을 봐주세요
- 없어용
- 디자인에 맞추서 색깔을 다시 지정할 수 있을거 같아요
=> [Fe] feature : nav progress bar

back-end/src/main/java/com/tdd/backend/post/Options.java, back-end/src/main/java/com/tdd/backend/post/Post.java, back-end/src/main/java/com/tdd/backend/post/RIDE_OPTION.java, back-end/src/main/java/com/tdd/backend/post/RideOption.java, back-end/src/main/resources/schema.sql, back-end/src/test/java/com/tdd/backend/post/PostServiceTest.java
- resolved #30 
- 코드 리팩토링을 했습니다.
- SUNLOOOP -> SUNROOF로 오타를 수정했습니다.
- 동승 여부를 Enum으로 나타내기 위해 리팩토링 했습니다. (RideOption 클래스 구현)
- ride_option, drive_career의 타입을 varchar(100)으로 변경하여 schema.sql에 적용했습니다.
- posts 테이블에 누락되어 있던 car_name 컬럼을 추가했습니다. 
- 이에 맞춰 Post 클래스에도 반영했습니다.
- 변수명, 클래스명이 적절한지 확인 부탁드립니다!
=> [BE]feature(#30) : 코드 리팩토링

.github/workflows/main.yml, back-end/dockerfile
- resolved #34 
- 워크플로우 사용을 위해 main.yml 생성
- 도커 생성을 위해 dokerfile 생성
- 깃허브 액션을 통해 도커 이미지 생성
- 깃허브 액션을 통해 도커 로그인 및 푸쉬
- 깃허브 액션을 통해 ec2 로그인 및 도커 이미지 생성
- main.yml을 한번씩 읽어보셨으면 합니다! 
- directory나 Path 설정을 틀리지 않게 잘해야합니다.
- 지금 이pr이 머지되는 순간이 첫 배포인데 에러가 없이 잘돌아가길 바랍니다..!......
- nginx도커 이미지도 생성하고 docker compose해야할거 같습니다.
=> [BE]feature(#34) : 백엔드 배포 자동화

.github/workflows/main.yml
- resolved #34
- path 를 찾지 못하는 오류
- 이전 테스트용 이미지 미삭제로 인한 포트 바인딩 중복 오류
- path 를 찾도록 디렉토리 이동 코드 추가
- 서버에 올라가 있는 테스트 이미지 삭제
- 도커 컴포즈로 프론트와 합칠 예정
- 성공
=> [BE]fix(#34) 자동 배포 수정

front-end/src/components/OptionForm/OptionForm.module.scss, front-end/src/components/OptionForm/OptionForm.ts, front-end/src/core/Store.ts, front-end/src/store/OptionStore/OptionStore.ts
- resolved #53
- 차량의 옵션을 선택하는 폼 구현
- 폼 (selector) 구현
- store에 데이터 저장 (OptionStore)
- 디자인과 애니메이션이 미흡해요.
- 아직 확인한 바는 없습니다.
- 디자인, 애니메이션 수정
- api 연결(get, post 둘다)
=> [Fe] feature(#53): car option selector

.env, front-end/src/core/Router.ts, front-end/src/pages/aboutus.ts
- resolved #n
- 
- 내용을 입력해주세요
- 
- 내용을 입력해주세요
- 
- 내용을 입력해주세요
- 
- 내용을 입력해주세요
- 
- 내용을 입력해주세요
- 
- 내용을 입력해주세요
=> fix: deploy 위해서 파일 소소한 수정

front-end/src/components/Clauses/Clauses.module.scss, front-end/src/components/Clauses/Clauses.ts, front-end/src/components/Clauses/template.ts
- resolved #62 
- 
- 약관페이지를 만들었어요
- 
- 약관페이지에 대한 내용 및 마크업을 만들었어요
- 
- 폰트를 어떻게 고칠지 고민해봤으면 좋겠어요
- 
- 아직 확인된 위험이나 장애는 없어요
- 
- 폰트 수정 및 글자 사이즈에 대한 협의 후 조정을 할 거에요
-
=> [FE]feature(#62 ): 홈페이지 마크업

.env, .github/workflows/main.yml, back-end/src/main/java/com/tdd/backend/user/UserController.java, front-end/dockerfile, front-end/package.json
- resolved #49 
- 프론트도 도커로 배포하도록 수정
- node dockerfile 작성
- docker-compose.yml 작성
- deploy에 사용되는 yml 수정 
- 오타 있는지 확인 부탁드립니다.
- 도커파일이 노출되어있습니다. 상관없나? 
- 도커도 환경변수나 깃허브 액션으로 숨길 예정입니다.
=> feature(#49) auto distribution

front-end/index.html, front-end/src/components/LoginForm/LoginForm.module.scss, front-end/src/components/LoginForm/LoginForm.ts, front-end/src/components/Navbar/Navbar.ts, front-end/src/main.ts, front-end/src/pages/aboutus.ts, front-end/src/styles/main.scss, front-end/src/utils/loginModal.ts, front-end/src/utils/overlay.ts
- resolved #93
- 로그인 폼을 이용해서 로그인을 하기 위해서 변경했어요
- 로그인 폼 구현
- api연결
- 네비게이션 바 버튼 스타일링
- 오버레이 구현
- 아직 백엔드 로그인 로직이 완성되어있지 않아서 로그인이나 가입은 되지 않아요
- 로그인, 회원 가입 로직을 추가해야 해요
=> #93: 로그인 폼 구현

front-end/src/components/ExperienceMap/ExperienceMap.ts, front-end/src/components/SharingMap/SharingMap.ts, front-end/src/utils/googleAPI.ts
- resolved #92 
- 지도를 Component식으로 리팩토링을 진행했어요.
- 지도데이터들을 props, state를 통해 관리할 필요가 있었어요.
- 위에 언급한 방식대로 코드 리팩토링을 진행했어요.
- 마커를 찍을 때 하나만 찍을 수 있어요.
- API를 load할 때 defer로 로드해요.
- state와 props를 맞게 사용했는지 확인해주세요.
- 경험하기에서 처음 지도가 렌더링 되기 전에 getBounds 호출이 일어나서 에러가 나요. 하지만 critical하지는 않아요.
- data를 가지고 내려와서 렌더링을 시켜보고 싶어요.
-
=> refactor(#92) 지도 리팩토링 및 기능 추가

back-end/src/main/java/com/tdd/backend/auth/CORSFilter.java
- resolved #108 
- 
- CORS 이슈
- 
- CORS filter 관련 Allow-Header 에 Authorization 헤더 추가
=> fix: CORS filter 관련 Allow-Header 에 Authorization 헤더 추가

front-end/src/components/Calendar/Calendar.ts, front-end/src/components/ExperienceMap/ExperienceMap.ts, front-end/src/components/SharingMap/SharingMap.ts
- resolved #97 
- Calendar에서 새로 렌더링될때 데이터가 사라지는 문제가 있었어요
- 임시로 작업했던 API Key가 노출되었어요
- Calendar에 props를 임의로 지정해줬어요
- process.env.APIKEY로 변경했어요  
- ### 리뷰어는 여기에 집중해주시면 좋아요
- 간단한 수정말 fix했습니다
- props를 제가 만들었기 때문에 추후에 props를 내려받는 과정이 필요해요
- 캘린더를 더 예쁘게 만들어야겠어요
=> fix(#97) 캘린더 데이터가 유지되지 않는 문제 수정 및 API Key 노출된 점 수정

front-end/src/components/Footer/Footer.ts, front-end/src/styles/main.scss
- resolved #116
- footer를 보이게 하기 위해서 변경했어요
- footer를 만들었어요
- 어떤 내용이 들어가면 좋을지 생각해주세요
- 아직 더미텍스트가 들어가 있어요
- 의미있는 내용으로 바꿀 예정이이에요
- 디자인 수정이 필요하다면 할 예정이에요
- tdd 로고도 넣을 예정이에요
=> feat(#116): footer 마크업

back-end/src/main/java/com/tdd/backend/user/UserController.java
- resolved #122 
- 이메일 중복을 디비에서 체크하는 API에 오타가 있어 수정함.
=> fix: email 중복 체크 API 오타 수정

front-end/src/components/MyPage/MyPage.module.scss, front-end/src/components/MyPage/MyPage.ts, front-end/src/components/MyPage/template.ts
- resolved #121 
- 마이페이지에 들어갈 간단한 마크업 작업
- 마이페이지에 들어갈 간단한 마크업 작업을 진행했습니다. 
- 유저 정보에 어떤 것이 더, 혹은 덜 필요한지 봐주세요
- 아직 모르겠습니다. 
- 임시로 만든 마크업이기 때문에 디자인이 엉망이라 수정해야 할 것 같아요
- 이 부분이 초기에 기획단계에서 빠져 있기 때문에 내일 같이 이야기 하면서 고쳐나가야할 것 같습니다.
=> feature(#121): 마이페이지 마크업

back-end/src/main/java/com/tdd/backend/exception/ExceptionController.java
- resolved #138 
- 충돌을 해결하던 와중 코드가 이상하게 들어간 부분이 있어서 수정하였습니다.
=> fix(#138) ExceptionController bug fix

.github/workflows/main.yml
- resolved #149 
- 테스트 때문에 건드린 코드 다시 원래대로 되돌렸습니다.
- 일단 boot jar 로 하기로 했습니다.
- 테스트 확인을 안합니다. 
- 유효한 테스트코드로 변경해야하지 않을까요..
=> fix(#149) deploy 되돌리기

front-end/src/components/DetailPage/DetailPage.module.scss, front-end/src/components/DetailPage/DetailPage.ts
- resolved #130 
- 글의 상세 페이지가 필요했어요
- 글의 상세 페이지에 들어갈 페이지의 마크업을 만들었어요
- 잘 부탁 드립니다. 
- 아직 없어용
- 디자인 수정 및 리팩토링, API 연동이 들어갈 예정입니다
=> feature(#130): 글 상세페이지 마크업

back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java, back-end/src/main/java/com/tdd/backend/post/data/DrivingDto.java, back-end/src/main/java/com/tdd/backend/post/repository/PostRepository.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java, back-end/src/test/java/com/tdd/backend/post/PostRepositoryTest.java
- resolved #141 
- 차량 이름, 옵션 리스트, 날짜 리스트를 받아서 해당 데이터들을 가지는 포스트를 전부 반환하는 메서드를 구현했어요.
- 옵션리스트, 날짜리스트틑 비어서 올 수 있기 때문에 경우를 4가지로 나누었어요.
- if문을 최대한 안쓰도록 리팩토링이 가능한지 봐주세요.
- 메서드명, 클래스명등이 적절하지 확인해주세요
- 전체적으로 코드 리팩토링이 가능한지, 개선 사항이 있는지 봐주세요!
=> feature(#141) driving rendering api

back-end/src/main/java/com/tdd/backend/mypage/exception/AppointmentNotFoundException.java, back-end/src/main/java/com/tdd/backend/mypage/exception/PostNotFoundException.java, back-end/src/main/java/com/tdd/backend/mypage/service/MyPageService.java, back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java, back-end/src/main/java/com/tdd/backend/post/controller/SharingController.java, back-end/src/main/java/com/tdd/backend/post/data/PostDto.java, back-end/src/main/java/com/tdd/backend/post/data/SharingDto.java, back-end/src/main/java/com/tdd/backend/post/exception/LocationNotFoundException.java, back-end/src/main/java/com/tdd/backend/post/model/Post.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java, back-end/src/main/java/com/tdd/backend/post/service/SharingService.java, back-end/src/test/http/driving.http, back-end/src/test/http/sharing.http, back-end/src/test/java/com/tdd/backend/post/PostRepositoryTest.java
- resolved #147 
- user id를 request body나 path variable로 받아왔는데 user token에서 받게되어 관련 코드 수정
- 미뤄뒀던 db optional exception 설정
- @UserLogin UserToken 사용하여 도큰 받아서 user id를 알아내어 사용했습니다.
- 예외 처리를 했습니다.
- 아직 db외에 다른 예외처리는 부족합니다.
- 테스트 코드를 작성해야합니다.
=> fix(#147) using jwt 하도록 사용부분 모두 수정

front-end/src/store/AuthStore.ts
- resolved #162
- 로그아웃하면 홈으로 리다이렉트 하고싶다는 백엔드분들의 요청
- 로그아웃으 하면 홈 화면으로 리다이렉트 하도록 했어요
=> fix(#162): 로그아웃하면 홈으로 리다이렉트

front-end/src/apis/login.ts, front-end/src/components/Navbar/Navbar.ts
- resolved #168
- 백엔드에서 logout ,test/auth 삭제
- logout시 api 호출하지 않음
- /test/auth -> /auth
=> fix(#168): delete logout api

back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java, back-end/src/main/java/com/tdd/backend/post/data/PostDto.java, back-end/src/main/java/com/tdd/backend/post/model/Post.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java, back-end/src/test/http/driving.http, back-end/src/test/http/myPage.http
- resolved #173 
- driving response에 post id가 필요해서 dto에 추가하고 로직을 변경했습니다.
- /test-driving/posts api에 오류가 나서 서비스 로직 수정했습니다.
- 쿼리 분기문에 isNull -> isEmpty로 변경했습니다.
- dto에 post id 추가하고 로직 수정했습니다.
- /test-driving/posts api 에 해당하는 .http 테스트 추가했습니다.
- 테스트 코드 작성해야합니다.
=> feature(#173) driving response에 post id 추가 및 자잘한 수정

front-end/src/apis/detailPage.ts, front-end/src/components/DetailPage/DetailPage.module.scss, front-end/src/components/DetailPage/DetailPage.ts
- resolved #182 
- API연동이 필요했어요
- API를 통해서 데이터를 받아오고 뿌려줘요.
- 전체적인 스타일링을 수정했어요.
- 메서드를 강제로 오버라이딩해서 사용했어요
- postId를 어떻게 받아올지 모르겠어요
- postId를 받아서 이 페이지를 렌더시켜야 할 것 같아요
- 가능하면 reverse geolocation으로 주소를 링크로 남기는 것이 아니라 실제로 보여주고 싶어요
=> api(#182): detailPage api 연동

back-end/src/main/java/com/tdd/backend/car/repository/CarRepository.java, back-end/src/main/java/com/tdd/backend/mypage/data/DefaultInfo.java, back-end/src/main/java/com/tdd/backend/mypage/service/MyPageService.java, back-end/src/main/java/com/tdd/backend/post/data/DrivingResponse.java, back-end/src/main/java/com/tdd/backend/post/model/Post.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java
- resolved #189 
- 이미지를 디비에서 받아오도록 수정해서 api도 이미지 url을 같이 응답하도록 구현했습니다.
- 이미지 url 가져오는 쿼리작성
- api response에 url 추가
- test-driving/posts에서도 url을 응답하고 있습니다.
=> feature(#189) add image to api 개발

back-end/src/main/java/com/tdd/backend/car/repository/CarRepository.java, back-end/src/main/java/com/tdd/backend/car/service/OptionService.java, back-end/src/main/java/com/tdd/backend/mypage/controller/MyCarController.java, back-end/src/main/java/com/tdd/backend/mypage/data/MyCarResponse.java, back-end/src/main/java/com/tdd/backend/mypage/repository/MyCarRepository.java, back-end/src/main/java/com/tdd/backend/mypage/service/MyPageService.java, back-end/src/main/java/com/tdd/backend/post/repository/PostRepository.java, back-end/src/test/http/mycar.http, back-end/src/test/java/com/tdd/backend/auth/encrypt/JwtEncryptTest.java, back-end/src/test/java/com/tdd/backend/mycar/MyCarServiceTest.java, back-end/src/test/java/com/tdd/backend/post/PostControllerTest.java, back-end/src/test/java/com/tdd/backend/post/PostRepositoryTest.java, back-end/src/test/java/com/tdd/backend/render/RenderControllerTest.java, back-end/src/test/java/com/tdd/backend/user/UserControllerTest.java
- resolved #206 
- 공유를 여러개 했을 때 오류
- 내차등록만 했을 때 오류
- 정보에 옵션리스트가 안나올때 오류
- 마이페이지 서비스 로직 수정
- post, Car 관련 쿼리 수정
- api 이름 수정
- 옵션 로그 삭제
- 쿼리에 문제가 있는지 검토 부탁드립니다.
- 리팩토링 및 테스트 코드 작성 예정입니다.
=> fix(#206) mypage 오류 수정

back-end/src/main/java/com/tdd/backend/mypage/repository/MyCarRepository.java, back-end/src/test/http/mycar.http
- resolved #208 
- mycar 아이디 맵핑 오류 수정
- as mycar_id 추가
- Get /mycars api test 추가
=> fix(#208) mycar 맵핑 오류 수정

front-end/src/apis/detailPage.ts, front-end/src/components/DetailPage/DetailPage.ts, front-end/src/components/MyPage/MyPage.ts
- resolved #217 
- detail Page에서 예약을 confirm해야했어요
- mypage에서 에러를 출력하고 있었어요
- detail Page에서 예약을 patch해줬어요
- 에러 출력을 없앴어요
- 잘 부탁 드립니다.
- 아직은 잘 모르겠어요
- 디자인 리팩토링
=> api(#217): detail Page api 연결 및 리팩토링

back-end/src/main/java/com/tdd/backend/post/repository/PostRepository.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java, back-end/src/test/java/com/tdd/backend/post/PostRepositoryTest.java
- resolved #219 
- 옵션 필터링 쿼리에서 문제가 발견되어 수정했어요!
- 쿼리 수정
- 변수, 메서드 네이밍 변경
=> fix(#219): 옵션으로 필터링할 때 잘못된 쿼리 수정, 메서드 및 변수 변경

.github/workflows/main.yml, back-end/src/main/java/com/tdd/backend/post/controller/SharingController.java, back-end/src/test/java/com/tdd/backend/post/PostControllerTest.java, back-end/src/test/java/com/tdd/backend/post/PostRepositoryTest.java, back-end/src/test/java/com/tdd/backend/user/UserControllerTest.java, back-end/src/test/java/com/tdd/backend/user/UserServiceTest.java, package-lock.json
- resolved #149 
- 배포 CI 적용
- 관련 테스트 모두 수정
- 테스트 배포 환경 가능하게 수정
- clean build로 빌드
- 안될 수도 있어요
=> fix/#149 deploy CI

front-end/index.html, front-end/src/apis/login.ts, front-end/src/components/DetailPage/DetailPage.ts, front-end/src/components/ExperienceMap/ExperienceMap.module.scss, front-end/src/components/ExperienceMap/ExperienceMap.ts, front-end/src/components/LoginForm/LoginForm.ts, front-end/src/components/MyPage/MyPage.ts, front-end/src/components/Navbar/Navbar.ts, front-end/src/components/RegisterCar/RegisterCar.ts, front-end/src/components/SharingForm/SharingForm.ts, front-end/src/components/SharingMap/SharingMap.module.scss, front-end/src/components/SharingMap/SharingMap.ts, front-end/src/constants/carList.ts, front-end/src/core/Router.ts, front-end/src/pages/sharing.ts, front-end/src/store/AuthStore.ts, front-end/src/store/OptionStore/DataHandler.ts, front-end/src/store/OptionStore/OptionStore.ts, front-end/src/store/OptionStore/interface.ts, front-end/src/store/RegisterStore/DataHandler.ts, front-end/src/styles/loadingSpinner.module.scss, front-end/src/styles/main.scss, front-end/src/utils/loadingSpinner.ts, front-end/src/utils/navigatator.ts, front-end/src/utils/notification.ts
- resolved #215
- 데이터가 극단적으로 많아졌을 때 받아오는 데이터의 양이 많아져서 느려요
- 그래서 map 정보도 넘겨서 해당 map 경계 내에 있는 데이터만 받아오기로 했어요
-  posts request body에 quad1 quad3 추가
-  맵 zoom 제한(12)
-  로딩 피드백 추가 - 로딩스피너
- 유저 사용성에 집중해주세요
- 
- 디자인을 개선해야할것 같아요..!
=> performance(#215): 경험하기 페이지 최적화, api 연결

front-end/src/components/MyPage/MyPage.ts, front-end/src/components/RegisterCar/RegisterCar.ts
- register에서 제대로 post되지 않는 문제
- register에서 제대로 post되지 않는 문제해결
- 에러 수정했습니다.
- 아직 모르겠어요
- 디자인 수정
-
=> fix(#withoutIssue): register에서 제대로 post되지 않는 문제

.github/workflows/main.yml, back-end/build.gradle, back-end/src/main/java/com/tdd/backend/exception/ExceptionController.java, back-end/src/main/java/com/tdd/backend/mypage/controller/MyPageController.java, back-end/src/main/java/com/tdd/backend/post/controller/DrivingController.java, back-end/src/main/java/com/tdd/backend/post/data/DrivingDto.java, back-end/src/main/java/com/tdd/backend/post/exception/ApprovalFailException.java, back-end/src/main/java/com/tdd/backend/post/repository/PostRepository.java, back-end/src/main/java/com/tdd/backend/post/service/DrivingService.java
- resolved #227 
- todo 내용들 해결
- 예약 서비스 예외처리
- 지난 날짜 필터링
- todo 내용들 해결
- 예약 서비스 예외처리 쿼리 수정
- 지난 날짜 필터링 쿼리 수정
=> refactor(#227) approve 예외, 날짜 예외 처리 등

front-end/src/components/CopyLinkBtn/CopyLinkBtn.module.scss, front-end/src/components/CopyLinkBtn/CopyLinkBtn.ts, front-end/src/components/ExperienceMap/ExperienceMap.module.scss, front-end/src/components/ExperienceMap/ExperienceMap.ts, front-end/src/components/LoginForm/LoginForm.ts, front-end/src/components/MyPage/MyPage.ts, front-end/src/components/Navbar/Navbar.ts, front-end/src/components/RegisterCar/RegisterCar.ts, front-end/src/components/SharingForm/SharingForm.module.scss, front-end/src/components/SharingForm/SharingForm.ts, front-end/src/components/SharingMap/SharingMap.module.scss, front-end/src/components/SharingMap/SharingMap.ts, front-end/src/constants/routeInfo.ts, front-end/src/pages/addcar.ts, front-end/src/pages/details.ts, front-end/src/pages/experiencing.ts, front-end/src/pages/mypage.ts, front-end/src/styles/loadingSpinner.module.scss
- resolved #225
- 
- 이슈에 올린 버그들이 있어서 해결했어요
- 커밋 단위 별로 해결한 내용 확인해주시면 좋을 것 같아요
- 
- 디자인 해주시면 좋을 것 같아요
=> fix(#225): 마무리로 찾은 이슈들 해결

front-end/src/components/BulletinBoard/BulletinBoard.module.scss, front-end/src/components/BulletinBoard/BulletinBoard.ts, front-end/src/components/Home/template.ts, front-end/src/components/Navbar/Navbar.module.scss
- resolved #236
- 게시글 제목 요청사항으로 보여주기
- 게시글 제목 요청사항으로 보여주기
=> design(#236): 게시글 제목 요청사항으로 보여주기

front-end/src/components/CopyLinkBtn/CopyLinkBtn.ts
- resolved #238
- 
- 링크 복사 붙여넣기 할수 있도록 인코딩
- 링크 복사 붙여넣기 할수 있도록 인코딩
=> fix(#238): 링크 복사 붙여넣기 할수 있도록 인코딩
